"""Regression tests for ``ignore_effective_charges``.

Background (see report/interpolation sec:cssni3-longrange and benchmark.md
section 19): ``ForceTensor.Tensor2.SetupFromPhonons`` subtracts the Ewald
dipole-dipole term from every commensurate block when the dynamical matrix
carries Born effective charges, centers/ASR-projects only the remainder, and
``Interpolate`` adds the Ewald term back.  That cycle is exactly the identity
on the coarse mesh, so no commensurate test can detect it; it acts only
between coarse points.  For an ensemble generated by a short-range potential
(a machine-learning force field, say) the stored Z*/eps are inherited
metadata and the cycle injects a dipole tail that is not in the data.

The toy chain is the sharpest possible probe: its force constants are
strictly range-1, so the plain centered Fourier continuation is EXACT at
every q, on-grid or off.  Any off-grid deviation is therefore entirely
attributable to the long-range cycle.
"""
import os
import sys

os.environ.setdefault("JULIA_NUM_THREADS", "1")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import pytest

import cellconstructor as CC
import cellconstructor.Methods

import _toy_chain as TC

try:
    import tdscha.QSpaceInterpolation as QI
    _OK = True
except Exception:
    _OK = False

pytestmark = pytest.mark.skipif(
    not _OK, reason="tdscha.QSpaceInterpolation not importable")

L = 4
Z_MAG = 2.0


def _dyn_with_charges():
    """Range-1 spring chain carrying (fictitious, neutral) Z* and eps."""
    dyn = TC.build_dyn(L)
    nat = dyn.structure.N_atoms
    zeu = np.zeros((nat, 3, 3))
    zeu[0] = +Z_MAG * np.eye(3)
    zeu[1] = -Z_MAG * np.eye(3)
    assert np.abs(zeu.sum(axis=0)).max() < 1e-12, "Z* must be neutral"
    dyn.effective_charges = zeu
    dyn.dielectric_tensor = np.diag([2.5, 2.5, 3.5])
    return dyn


def _fine_q(dyn, fine):
    return QI.generate_fine_mesh(dyn.structure, (1, 1, fine))[0]


def test_ignore_flag_does_not_mutate_the_caller_dyn():
    """Scope guarantee: IR/Raman consumers downstream must still see Z*.

    The flag hides the charges from the Tensor2 built inside
    interpolate_dyn_fine only; it must never strip them from the caller's
    dynamical matrix.
    """
    dyn = _dyn_with_charges()
    zeu_before = dyn.effective_charges.copy()
    eps_before = dyn.dielectric_tensor.copy()

    QI.interpolate_dyn_fine(dyn, _fine_q(dyn, 2 * L),
                            ignore_effective_charges=True)

    assert dyn.effective_charges is not None
    assert dyn.dielectric_tensor is not None
    assert np.allclose(dyn.effective_charges, zeu_before)
    assert np.allclose(dyn.dielectric_tensor, eps_before)


def test_default_is_to_use_the_charges():
    """Opt-in, not opt-out: the default must remain the cellconstructor
    behaviour, since for a genuinely polar potential it is the correct one."""
    dyn = _dyn_with_charges()
    q_fine = _fine_q(dyn, 2 * L)

    w_default, _ = QI.interpolate_dyn_fine(dyn, q_fine)
    w_used, _ = QI.interpolate_dyn_fine(dyn, q_fine,
                                        ignore_effective_charges=False)
    assert np.allclose(w_default, w_used)


def test_commensurate_limit_is_blind_to_the_flag():
    """The subtract/re-add cycle cancels identically on the coarse mesh.

    This is exactly why the bug survived every regression test in the suite,
    and it is worth pinning: a commensurate check can never discriminate the
    two conventions.
    """
    dyn = _dyn_with_charges()
    q_coarse = _fine_q(dyn, L)

    w_used, _ = QI.interpolate_dyn_fine(dyn, q_coarse, use_asr=False,
                                        reuse_commensurate=False,
                                        ignore_effective_charges=False)
    w_ignored, _ = QI.interpolate_dyn_fine(dyn, q_coarse, use_asr=False,
                                           reuse_commensurate=False,
                                           ignore_effective_charges=True)
    assert np.allclose(w_used, w_ignored, atol=1e-9), (
        "on the coarse mesh the two conventions must agree to machine "
        "precision")


def test_ignoring_charges_is_exact_for_the_range1_model():
    """The chain's force constants are strictly range-1, so the plain
    Fourier continuation reproduces the exact dynamical matrix at ANY q."""
    dyn = _dyn_with_charges()
    fine = 2 * L
    q_fine = _fine_q(dyn, fine)

    w_ignored, _ = QI.interpolate_dyn_fine(dyn, q_fine, use_asr=False,
                                           reuse_commensurate=False,
                                           ignore_effective_charges=True)

    # exact reference: the same chain built directly on the fine supercell
    dyn_fine = TC.build_dyn(fine)
    bg = dyn.structure.get_reciprocal_vectors() / (2 * np.pi)
    m3 = np.repeat(dyn.structure.get_masses_array(), 3)
    inv_sqrt_mm = 1.0 / np.sqrt(np.outer(m3, m3))

    worst = 0.0
    for q in q_fine:
        jq = min(range(len(dyn_fine.q_tot)),
                 key=lambda j: CC.Methods.get_min_dist_into_cell(
                     bg, np.asarray(q), np.asarray(dyn_fine.q_tot[j])))
        D = dyn_fine.dynmats[jq] * inv_sqrt_mm
        D = 0.5 * (D + np.conj(D.T))
        e = np.linalg.eigvalsh(D)
        w_ref = np.sign(e) * np.sqrt(np.abs(e))
        iq = min(range(len(q_fine)),
                 key=lambda i: CC.Methods.get_min_dist_into_cell(
                     bg, np.asarray(q), np.asarray(q_fine[i])))
        worst = max(worst, np.abs(np.sort(w_ignored[:, iq]) - np.sort(w_ref)).max())

    assert worst < 1e-8, (
        "ignore_effective_charges=True must be exact for a range-1 model, "
        "got {:.3e} Ry".format(worst))


def test_charges_corrupt_the_offgrid_continuation():
    """The whole point: with the charges used, the same range-1 model is no
    longer reproduced off-grid, even though it is exact on-grid."""
    dyn = _dyn_with_charges()
    fine = 2 * L
    q_fine = _fine_q(dyn, fine)

    w_used, _ = QI.interpolate_dyn_fine(dyn, q_fine, use_asr=False,
                                        reuse_commensurate=False,
                                        ignore_effective_charges=False)
    w_ignored, _ = QI.interpolate_dyn_fine(dyn, q_fine, use_asr=False,
                                           reuse_commensurate=False,
                                           ignore_effective_charges=True)

    # off-grid points: fine index odd along the chain direction
    frac = np.array([dyn.structure.unit_cell @ q for q in q_fine])
    n_z = np.round(frac[:, 2] * fine).astype(int) % fine
    off = (n_z % (fine // L)) != 0
    assert off.any(), "the fine mesh must contain off-grid points"

    assert np.abs(w_used[:, ~off] - w_ignored[:, ~off]).max() < 1e-9, (
        "the conventions must coincide on the coarse points")
    assert np.abs(w_used[:, off] - w_ignored[:, off]).max() > 1e-6, (
        "the long-range cycle must visibly displace the off-grid "
        "continuation of a range-1 model -- if this ever fails, the "
        "subtract/re-add path in cellconstructor has changed")
